[build]
  command = "python scripts/build.py"
  publish = "public"
  functions = "netlify/functions"  # Add this line for functions

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/city/*"
  to = "/city/:splat/index.html"
  status = 200

# Add this redirect for the search API function
[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  command = "python -m http.server -d public"
  port = 8888
  publish = "public"
